// Скіни карток — дослівна копія SKINS з SlotOK (openCardColorPicker у
// slotok app.js). SlotOK пише обраний id у users/<nick>/virtualCard/skin;
// тут ми лише відображаємо його. Додали скін у SlotOK — додай і сюди.
const SLOTOK_SKINS = [
    // Класика
    {id:'gold',     name:'Золото',     accent:'#d4af37', prev:'linear-gradient(135deg,#1a0d00,#3a2200)'},
    {id:'onyx',     name:'Онікс',      accent:'#ddd',    prev:'linear-gradient(135deg,#000,#1a1a1a)'},
    {id:'platinum', name:'Платина',    accent:'#dcdce6', prev:'linear-gradient(135deg,#1a1a1d,#2c2c30)'},
    {id:'copper',   name:'Мідь',       accent:'#dc823c', prev:'linear-gradient(135deg,#1f0d00,#4a2200)'},
    {id:'minimal',  name:'Мінімал',    accent:'#333',    prev:'linear-gradient(160deg,#e8e8e8,#f5f5f5)'},
    // Самоцвіти
    {id:'sapphire', name:'Сапфір',     accent:'#4a9eff', prev:'linear-gradient(135deg,#000d1a,#002a55)'},
    {id:'emerald',  name:'Смарагд',    accent:'#3dd68c', prev:'linear-gradient(135deg,#001a0f,#003d24)'},
    {id:'amethyst', name:'Аметист',    accent:'#b450ff', prev:'linear-gradient(135deg,#1a0025,#33004d)'},
    {id:'rosegold', name:'Рожеве золото', accent:'#e6aaa0', prev:'linear-gradient(135deg,#2a1015,#4a2a28)'},
    {id:'coral',    name:'Корал',      accent:'#ff7f6e', prev:'linear-gradient(135deg,#1a0510,#330a1f)'},
    // Стихії
    {id:'fire',     name:'Вогонь',     accent:'#ff6400', prev:'linear-gradient(160deg,#1a0000,#4a1000)'},
    {id:'ice',      name:'Лід',        accent:'#96dcff', prev:'linear-gradient(150deg,#001a2a,#003350)'},
    {id:'mint',     name:'М\'ята',     accent:'#64ffd2', prev:'linear-gradient(135deg,#001a15,#003328)'},
    {id:'storm',    name:'Гроза',      accent:'#9696c8', prev:'linear-gradient(160deg,#05050a,#14141f)'},
    {id:'sunset',   name:'Захід',      accent:'#ff698c', prev:'linear-gradient(135deg,#4a1428,#3a1a08)'},
    // Космос і футуризм
    {id:'cyber',    name:'Кібер',      accent:'#00ffdc', prev:'linear-gradient(135deg,#000814,#001d3d)'},
    {id:'galaxy',   name:'Галактика',  accent:'#b48cff', prev:'linear-gradient(160deg,#0a0020,#1a0040)'},
    {id:'holo',     name:'Голограма',  accent:'#fff',    prev:'linear-gradient(120deg,#ff2ecc,#ffd12e,#2effc7,#2e6bff)'},
    // Текстури
    {id:'carbon',   name:'Карбон',     accent:'#aaa',    prev:'repeating-linear-gradient(45deg,#0a0a0a,#0a0a0a 4px,#1a1a1a 4px,#1a1a1a 8px)'},
    {id:'marble',   name:'Мармур',     accent:'#eee',    prev:'linear-gradient(160deg,#26262e,#1a1a22)'},
    {id:'denim',    name:'Джинс',      accent:'#6496dc', prev:'linear-gradient(160deg,#0a1a2e,#14304f)'},
    {id:'snake',    name:'Змія',       accent:'#78c878', prev:'linear-gradient(150deg,#0d1a0d,#1a2e1a)'},
    {id:'leopard',  name:'Леопард',    accent:'#c89650', prev:'linear-gradient(150deg,#3a2410,#4a3018)'},
    // Особливі
    {id:'pastel',   name:'Пастель',    accent:'#ffc8e6', prev:'linear-gradient(135deg,#2a1f2e,#3a2a40)'},
    {id:'xmas',     name:'Новий рік',  accent:'#ffd700', prev:'linear-gradient(135deg,#0a1a0a,#1a0505)'},
    {id:'ukraine',  name:'Україна',    accent:'#ffd700', prev:'linear-gradient(180deg,#0057b7 50%,#ffd700 50%)'},
    // Класика (нові)
    {id:'silver',   name:'Срібло',     accent:'#c8c8d2', prev:'linear-gradient(135deg,#1a1a1c,#3a3a3e)'},
    {id:'bronze',   name:'Бронза',     accent:'#cd7f32', prev:'linear-gradient(135deg,#1f1206,#4a2e12)'},
    {id:'obsidian', name:'Обсидіан',   accent:'#a050e0', prev:'linear-gradient(150deg,#050208,#180a2a)'},
    {id:'steel',    name:'Сталь',      accent:'#8caac8', prev:'linear-gradient(135deg,#0d1218,#2a3642)'},
    {id:'ivory',    name:'Слонова кістка', accent:'#3a3020', prev:'linear-gradient(160deg,#efe9dd,#f8f4ea)'},
    {id:'charcoal', name:'Вугілля',    accent:'#ddd',    prev:'linear-gradient(135deg,#0a0a0a,#232323)'},
    {id:'chrome',   name:'Хром',       accent:'#dcdce6', prev:'linear-gradient(120deg,#2c2c30,#dcdce6)'},
    // Самоцвіти (нові)
    {id:'ruby',     name:'Рубін',      accent:'#dc143c', prev:'linear-gradient(135deg,#1a0004,#4a0012)'},
    {id:'topaz',    name:'Топаз',      accent:'#ffc440', prev:'linear-gradient(135deg,#1f1600,#4a3800)'},
    {id:'opal',     name:'Опал',       accent:'#e6ccff', prev:'linear-gradient(120deg,#1a1a2a,#dcc8ff)'},
    {id:'garnet',   name:'Гранат',     accent:'#8c1e2d', prev:'linear-gradient(135deg,#1a0505,#3a0a10)'},
    {id:'turquoise',name:'Бірюза',     accent:'#40e0d0', prev:'linear-gradient(135deg,#001a1a,#003d3d)'},
    {id:'citrine',  name:'Цитрин',     accent:'#ffa528', prev:'linear-gradient(135deg,#1a1200,#4a3200)'},
    {id:'peridot',  name:'Перидот',    accent:'#b4dc3c', prev:'linear-gradient(135deg,#0f1a00,#2a3d00)'},
    // Стихії (нові)
    {id:'thunder',  name:'Грім',       accent:'#8c8cff', prev:'linear-gradient(135deg,#050510,#1a1a4a)'},
    {id:'earth',    name:'Земля',      accent:'#96aa50', prev:'linear-gradient(135deg,#0f1005,#2a2a10)'},
    {id:'volcano',  name:'Вулкан',     accent:'#ff5000', prev:'linear-gradient(160deg,#0a0000,#4a0a00)'},
    {id:'blizzard', name:'Хуртовина',  accent:'#c8e6ff', prev:'linear-gradient(150deg,#0a1420,#2a4a6a)'},
    {id:'tsunami',  name:'Цунамі',     accent:'#3c96dc', prev:'linear-gradient(150deg,#00080f,#003250)'},
    {id:'solar',    name:'Сонце',      accent:'#ffb428', prev:'linear-gradient(135deg,#1a0e00,#4a2800)'},
    {id:'void',     name:'Порожнеча', accent:'#a064dc', prev:'linear-gradient(150deg,#000,#150022)'},
    // Космос і футуризм (нові)
    {id:'nebula',   name:'Туманність', accent:'#c850ff', prev:'linear-gradient(135deg,#0a0018,#3a0050)'},
    {id:'matrix',   name:'Матриця',    accent:'#00ff50', prev:'linear-gradient(160deg,#000800,#003300)'},
    {id:'synthwave',name:'Синтвейв',   accent:'#ff2ea6', prev:'linear-gradient(120deg,#1a0028,#ff2ea6)'},
    {id:'aurora',   name:'Аврора',     accent:'#00ff9c', prev:'linear-gradient(120deg,#001a12,#00ff9c)'},
    {id:'plasma',   name:'Плазма',     accent:'#ff2ecc', prev:'linear-gradient(120deg,#1a0018,#ff2ecc)'},
    {id:'quantum',  name:'Квант',      accent:'#50b4ff', prev:'linear-gradient(135deg,#000a1a,#0050a0)'},
    // Текстури (нові)
    {id:'wood',     name:'Дерево',     accent:'#a06e3c', prev:'linear-gradient(100deg,#1f1206,#3a2410)'},
    {id:'concrete', name:'Бетон',      accent:'#a0a0a0', prev:'linear-gradient(135deg,#141414,#2e2e2e)'},
    {id:'velvet',   name:'Оксамит',    accent:'#a01478', prev:'linear-gradient(135deg,#12000f,#3a0028)'},
    {id:'silk',     name:'Шовк',       accent:'#c8beDC', prev:'linear-gradient(120deg,#1e1a24,#3a3244)'},
    {id:'brushedmetal', name:'Шліфований метал', accent:'#d2d2dc', prev:'linear-gradient(95deg,#26262a,#3e3e44)'},
    {id:'camo',     name:'Камуфляж',   accent:'#788c50', prev:'linear-gradient(120deg,#0f1a0a,#2a3318)'},
    // Особливі (нові)
    {id:'halloween',name:'Гелловін',   accent:'#ff8200', prev:'linear-gradient(135deg,#0a0000,#3a1500)'},
    {id:'valentine',name:'Валентинка', accent:'#ff3c6e', prev:'linear-gradient(135deg,#1a0008,#4a001a)'},
    {id:'easter',   name:'Великдень',  accent:'#ffd8e8', prev:'linear-gradient(120deg,#1a1420,#ffd8e8)'},
    {id:'autumn',   name:'Осінь',      accent:'#ff8c28', prev:'linear-gradient(135deg,#1a0d00,#4a2400)'},
    {id:'spring',   name:'Весна',      accent:'#78dc96', prev:'linear-gradient(135deg,#001a08,#0d3d1a)'},
    {id:'diamondelite', name:'Діамант Еліт', accent:'#e8e8f5', prev:'linear-gradient(115deg,#0a0a0f,#e8e8f5)'},
    {id:'midnight', name:'Північ',     accent:'#5050c8', prev:'linear-gradient(160deg,#000005,#050518)'},
    // Меми (тягнуться напряму з i.imgflip.com)
    {id:'meme-drake',            name:'Drake',           accent:'#fff', prev:"url('https://i.imgflip.com/30b1gx.jpg') center/cover"},
    {id:'meme-distracted',       name:'Хлопець і дівчина', accent:'#fff', prev:"url('https://i.imgflip.com/1ur9b0.jpg') center/cover"},
    {id:'meme-womancat',         name:'Жінка й кіт',     accent:'#fff', prev:"url('https://i.imgflip.com/345v97.jpg') center/cover"},
    {id:'meme-twobuttons',       name:'Дві кнопки',      accent:'#fff', prev:"url('https://i.imgflip.com/1g8my4.jpg') center/cover"},
    {id:'meme-changemymind',     name:'Переконай мене',  accent:'#fff', prev:"url('https://i.imgflip.com/24y43o.jpg') center/cover"},
    {id:'meme-successkid',       name:'Success Kid',     accent:'#fff', prev:"url('https://i.imgflip.com/1bhk.jpg') center/cover"},
    {id:'meme-doge',             name:'Doge',            accent:'#fff', prev:"url('https://i.imgflip.com/4t0m5.jpg') center/cover"},
    {id:'meme-thisisfine',       name:'This is Fine',    accent:'#fff', prev:"url('https://i.imgflip.com/wxica.jpg') center/cover"},
    {id:'meme-stonks',           name:'Stonks',          accent:'#fff', prev:"url('https://i.imgflip.com/3si4.jpg') center/cover"},
    {id:'meme-rollsafe',         name:'Roll Safe',       accent:'#fff', prev:"url('https://i.imgflip.com/1h7in3.jpg') center/cover"},
    {id:'meme-pikachu',          name:'Здивований Пікачу', accent:'#fff', prev:"url('https://i.imgflip.com/2kbn1e.jpg') center/cover"},
    {id:'meme-disastergirl',     name:'Disaster Girl',   accent:'#fff', prev:"url('https://i.imgflip.com/23ls.jpg') center/cover"},
    {id:'meme-grumpycat',        name:'Grumpy Cat',      accent:'#fff', prev:"url('https://i.imgflip.com/8p0a.jpg') center/cover"},
    {id:'meme-expandingbrain',   name:'Галактичний мозок', accent:'#fff', prev:"url('https://i.imgflip.com/1jwhww.jpg') center/cover"},
    {id:'meme-onedoesnotsimply', name:'One Does Not Simply', accent:'#fff', prev:"url('https://i.imgflip.com/1bij.jpg') center/cover"},
    {id:'meme-ancientaliens',    name:'Древні прибульці', accent:'#fff', prev:"url('https://i.imgflip.com/26am.jpg') center/cover"},
    {id:'meme-dicaprio',         name:'ДіКапріо',        accent:'#fff', prev:"url('https://i.imgflip.com/39t1o.jpg') center/cover"},
    {id:'meme-pigeon',           name:'Це голуб?',       accent:'#fff', prev:"url('https://i.imgflip.com/1o00in.jpg') center/cover"},
    {id:'meme-batman',           name:'Бетмен ляпас',    accent:'#fff', prev:"url('https://i.imgflip.com/9ehk.jpg') center/cover"},
    {id:'meme-spongebob',        name:'Губка Боб',       accent:'#fff', prev:"url('https://i.imgflip.com/1otk96.jpg') center/cover"},
    {id:'meme-sadpablo',         name:'Сумний Пабло',    accent:'#fff', prev:"url('https://i.imgflip.com/1c1uej.jpg') center/cover"},
    {id:'meme-hidethepain',      name:'Hide the Pain',   accent:'#fff', prev:"url('https://i.imgflip.com/gk5el.jpg') center/cover"},
    // Свіжі "молодіжні" тренд-меми
    {id:'meme-67kid',       name:'6-7',               accent:'#fff', prev:"url('https://i.imgflip.com/4/a9fxer.jpg') center/cover"},
    {id:'meme-skibidi',     name:'Skibidi Toilet',    accent:'#fff', prev:"url('https://i.imgflip.com/4/7mzkd0.jpg') center/cover"},
    {id:'meme-tralalero',   name:'Tralalero Tralala', accent:'#fff', prev:"url('https://i.imgflip.com/4/9p82jm.jpg') center/cover"},
    {id:'meme-bombardiro',  name:'Bombardiro Crocodilo', accent:'#fff', prev:"url('https://i.imgflip.com/4/9q3kcu.jpg') center/cover"},
    {id:'meme-tungtung',    name:'Tung Tung Sahur',   accent:'#fff', prev:"url('https://i.imgflip.com/4/9r9m7h.jpg') center/cover"},
    {id:'meme-chimpanzini', name:'Chimpanzini Bananini', accent:'#fff', prev:"url('https://i.imgflip.com/4/9r9mu1.jpg') center/cover"},
    {id:'meme-gigachad',    name:'Gigachad',          accent:'#fff', prev:"url('https://i.imgflip.com/2/6x0oo0.jpg') center/cover"},
    {id:'meme-sigma',       name:'Sigma',             accent:'#fff', prev:"url('https://i.imgflip.com/4/5imrkq.jpg') center/cover"},
    {id:'meme-chillguy',    name:'Chill Guy',         accent:'#fff', prev:"url('https://i.imgflip.com/4/9au02y.jpg') center/cover"},
    {id:'meme-ohio',        name:'Ohio',              accent:'#fff', prev:"url('https://i.imgflip.com/4/46e43q.jpg') center/cover"},
    {id:'meme-npc',         name:'NPC',               accent:'#fff', prev:"url('https://i.imgflip.com/4/2k0qad.jpg') center/cover"},
    {id:'meme-rizzler',     name:'Rizzler',           accent:'#fff', prev:"url('https://i.imgflip.com/4/93etli.jpg') center/cover"},
];

// Категорії — теж з openCardColorPicker у SlotOK.
const SLOTOK_SKIN_CATEGORIES = [
    { name:'✨ Класика', ids:['gold','onyx','platinum','copper','minimal','silver','bronze','obsidian','steel','ivory','charcoal','chrome'] },
    { name:'💎 Самоцвіти', ids:['sapphire','emerald','amethyst','rosegold','coral','ruby','topaz','opal','garnet','turquoise','citrine','peridot'] },
    { name:'🌪️ Стихії', ids:['fire','ice','mint','storm','sunset','thunder','earth','volcano','blizzard','tsunami','solar','void'] },
    { name:'🚀 Космос і футуризм', ids:['cyber','galaxy','holo','nebula','matrix','synthwave','aurora','plasma','quantum'] },
    { name:'🪨 Текстури', ids:['carbon','marble','denim','snake','leopard','wood','concrete','velvet','silk','brushedmetal','camo'] },
    { name:'🎉 Особливі', ids:['pastel','xmas','ukraine','halloween','valentine','easter','autumn','spring','diamondelite','midnight'] },
    { name:'🎭 Меми', ids:['meme-drake','meme-distracted','meme-womancat','meme-twobuttons','meme-changemymind','meme-successkid','meme-doge','meme-thisisfine','meme-stonks','meme-rollsafe','meme-pikachu','meme-disastergirl','meme-grumpycat','meme-expandingbrain','meme-onedoesnotsimply','meme-ancientaliens','meme-dicaprio','meme-pigeon','meme-batman','meme-spongebob','meme-sadpablo','meme-hidethepain'] },
    { name:'🔥 Тренди зумерів', ids:['meme-67kid','meme-skibidi','meme-tralalero','meme-bombardiro','meme-tungtung','meme-chimpanzini','meme-gigachad','meme-sigma','meme-chillguy','meme-ohio','meme-npc','meme-rizzler'] },
];
